version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            pwd
            ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bd:f8:e1:26:83:67:9f:d7:33:a2:a7:58:3c:8f:84:35"
            - "d2:1b:eb:c8:23:41:58:44:6f:c9:01:24:ab:34:e5:5b"
      - run:
          name: "despliegue desarrollo"
          command: |
            scp index.html ubuntu@3.227.253.49:/
            
  
workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two
