version:
jobs:
  initial:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - run: echo "Prueba de comandos"
    - run:
        name: test one
        command: |
          ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@ec2-100-25-43-172.compute-1.amazonaws.com "touch ~/hola |
          ls | 
          hostname -i"            
  developdeploy:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - d7:78:96:12:2d:73:19:01:c2:41:25:5a:2a:f0:28:a8
    - run:
        name: despliegue desarrollo
        command: |
          ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@ec2-100-25-43-172.compute-1.amazonaws.com sudo chmod 777 /var/www/html
          scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r index.html ubuntu@ec2-100-25-43-172.compute-1.amazonaws.com:/var/www/html
          scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r view ubuntu@ec2-100-25-43-172.compute-1.amazonaws.com:/var/www/html
  
  production-deploy1:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - fa:15:45:6e:89:63:27:2b:43:82:d6:0a:42:be:a2:08
    - run:
        name: despliegue 1
        command: |
          ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@3.133.149.127 "sudo chmod 777 ~/"
          scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r index.html ubuntu@3.133.149.127:~/
                  ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@3.133.149.127 "
                  sudo chmod 400 "qwerty.pem"
                  sudo ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i "qwerty.pem" ubuntu@10.0.2.74 "sudo chmod 777 /var/www/html" |
                  sudo scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r -i "qwerty.pem" ~/index.html ubuntu@10.0.2.74:/var/www/html"
  
  production-deploy2:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - fa:15:45:6e:89:63:27:2b:43:82:d6:0a:42:be:a2:08
    - run:
        name: despliegue 2
        command: |
          ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@3.133.149.127 "sudo chmod 777 ~/"
          scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r index.html ubuntu@3.133.149.127:~/
                  ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@3.133.149.127 "
                  sudo chmod 400 "qwerty.pem"
                  sudo ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i "qwerty.pem" ubuntu@10.0.2.150 "sudo chmod 777 /var/www/html" |
                  sudo scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r -i "qwerty.pem" ~/index.html  ubuntu@10.0.2.150:/var/www/html"    

      
workflows:
  version: 2
  prueba:
    jobs:
    - initial
    - developdeploy:
        requires:
        - initial
    - hold:
        type: approval
        requires:
        - developdeploy
    - production-deploy1:
        requires:
        - hold
    - production-deploy2:
        requires:
        - hold
