version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            pwd
            ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: "despliegue desarrollo"
          command: |
            chmod 400 Key_parcial_3.pem
            scp -i "Key_parcial_3.pem" index.html ubuntu@3.227.253.49:/var
            
            
  
workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two
