version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          commnad: |
            touch hola
            ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: 
          name: "test two"
          commnad: |
            touch Carlos
            ls
  three:
    docker:
      - image: builtpack-deps:trusty
    steps:
      - checkout
      - run: pwd
      - run: ls

workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two:
          requires:
            - one
      - three:
          requires:
            - two
