version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            touch hola
            ls
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - ./
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: 
          name: "test two"
          command: |
            touch Carlos
            ls
  three:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: pwd
      - run: ls

workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two:
          requires:
            - one
      - three:
          requires:
            - two
