version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            pwd
            ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: "despliegue desarrollo"
          command: |
            chmod 400 Key3.pem
            scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r -i "Key3.pem" index.html ubuntu@ec2-18-205-66-124.compute-1.amazonaws.com:~/
            
  
workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two
