version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: |
          - touch hola
          - ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: pwd
      - run: ls

workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two
