version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            pwd
            ls
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d7:78:96:12:2d:73:19:01:c2:41:25:5a:2a:f0:28:a8"
      - run:
          name: "despliegue desarrollo"
          command: |
            ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null ubuntu@ec2-18-205-66-124.compute-1.amazonaws.com sudo chmod 766 /var/www/html
            scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -r index.html ubuntu@ec2-18-205-66-124.compute-1.amazonaws.com:/var/www/html
            
  
workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two
