version:
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: 
          name: "test one"
          command: |
            pwt
            ls
workflows:
  version: 2
  prueba:
    jobs:
      - one
      - two:
          requires:
            - one
      - three:
          requires:
            - two
